# Generated by Django 4.0.5 on 2022-06-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_category_product_alter_foreign_keys"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(default=None, max_length=100, unique=True),
        ),
    ]
