version: "3.8"
services:
  djang_shop:
    restart: always
    build:
      context: .
      dockerfile: ./DjangoShop/Dockerfile
    ports:
      - 8000:8000
    expose:
      - 8000
    environment:
      - POSTGRES_DB=${POSTGRES_DB:?err}
      - POSTGRES_USER=${POSTGRES_USER:?err}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?err}
    volumes:
      - .:/app
    container_name: django_app
    depends_on:
      - postgres_db
  postgres_db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB:?err}
      - POSTGRES_USER=${POSTGRES_USER:?err}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?err}
    container_name: postgres_db
